#!/usr/bin/env bash
# Installs nginx and configures a 301 redirect from /redirect_me to YouTube

apt-get update
apt-get install -y nginx

# Add 301 redirect to nginx config
sed -i '/server_name _;/a \\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart nginx using service
service nginx restart 