#!/usr/bin/env bash
# Installs nginx and configures a custom 404 page with the string 'Ceci n\'est pas une page'

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Add custom 404 config to nginx
sed -i '/server_name _;/a \    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart nginx using service
service nginx restart 