#!/usr/bin/env bash
# Configures nginx to return a custom X-Served-By header with the server's hostname

# Update package list
apt-get update

# Install nginx
apt-get install -y nginx

# Add custom header to nginx config
sed -i '/^\s*server_name _;/a \
    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Reload nginx
service nginx reload 