#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Install and configure HAproxy on the lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\

frontend  mycall123-frontend
        bind *:80
        mode http
        default_backend mycall123-backend

backend mycall123-backend
        balance roundrobin
        server web-01 3.83.23.24 check
        server web-02 3.83.128.168 check

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
